services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 3030:3030 # HTTP API Port for rqbit
      - 4240:4240 # TCP BitTorrent Port for rqbit
      - 8888:8888/tcp 
      - 8388:8388/tcp 
      - 8388:8388/udp 
    volumes:
      - /gluetun:/gluetun
    environment:
      ## BASE GLUETUN CONFIGURATION
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER={INSERT HERE}
      - VPN_TYPE={INSERT HERE}
      
      # COMMENT OUT "- OPENVPN_(...)" NOT IN-USE
      # OpenVPN:
      - OPENVPN_USER={INSERT HERE}
      - OPENVPN_PASSWORD={INSERT HERE}
      
      # COMMENT OUT "- WIREGUARD_(...)" IF NOT IN-USE
      # Wireguard:
      #- WIREGUARD_PRIVATE_KEY={Insert HERE}
      #- WIREGUARD_ADDRESSES={INSERT HERE}

      ## END GLUETUN CONFIGURATION
  rqbit:
    image: ikatson/rqbit:latest
    container_name: rqbit
    network_mode: "service:gluetun"
    depends_on:
      - gluetun 
    volumes: 
     - rqbitDB:/home/rqbit/db
     - rqbitCache:/home/rqbit/cache
     - /home/downloads:/home/rqbit/downloads
volumes:
  rqbitDB: {}
  rqbitCache: {}